# Generated by Django 5.2 on 2025-04-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100, verbose_name='Kоманда:1')),
                ('team2', models.CharField(max_length=100, verbose_name='Kоманда:2')),
                ('odds_team1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_draw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_team2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField(verbose_name='Начало тайма')),
                ('is_finished', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('draw', 'Draw')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_options', to='matches.match')),
            ],
        ),
    ]
