# Generated by Django 5.2 on 2025-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('draw', 'Draw')], max_length=20, null=True)),
            ],
        ),
    ]
