# Generated by Django 5.2 on 2025-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_remove_bet_option'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='chance_team1',
            field=models.CharField(default=1, max_length=5, verbose_name='Шансы команды_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='chance_team2',
            field=models.CharField(default=1, max_length=5, verbose_name='Шансы команды_2'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BetOption',
        ),
    ]
