# Generated by Django 5.2 on 2025-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_chance_team1_match_chance_team2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='odds_draw',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициенты команды_2 '),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_team1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициенты команды_1 '),
        ),
    ]
