# Generated by Django 5.2 on 2025-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_odds_draw_alter_match_odds_team1'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='chance_draw',
            field=models.CharField(default=1, max_length=5, verbose_name='Шансы ничьи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_draw',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициенты ничьи'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_team1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициенты команды_1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_team2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициенты команды_2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(max_length=20, verbose_name='Начало тайма'),
        ),
    ]
