# Generated by Django 5.2 on 2025-04-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_chance_draw_alter_match_odds_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
