# Generated by Django 5.2 on 2025-04-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-start_time'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
    ]
