# Generated by Django 5.2 on 2025-04-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_bet_amount_alter_bet_chosen_winner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'verbose_name': 'Ставка', 'verbose_name_plural': 'Ставки'},
        ),
    ]
