# Generated by Django 5.2 on 2025-04-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='option',
        ),
    ]
