# Generated by Django 5.2 on 2025-04-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_alter_bet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-amount'], 'verbose_name': 'Ставка', 'verbose_name_plural': 'Ставки'},
        ),
    ]
