# Generated by Django 5.2 on 2025-04-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_remove_bet_option'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matches.betoption'),
            preserve_default=False,
        ),
    ]
