# Generated by Django 5.2 on 2025-04-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_bet_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='option',
        ),
    ]
