# Generated by Django 5.2 on 2025-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_remove_bet_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='chosen_winner',
            field=models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('draw', 'Draw')], max_length=20, verbose_name='Исход матча'),
        ),
    ]
