# Generated by Django 5.2 on 2025-04-16 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_alter_bet_chosen_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
