# Generated by Django 5.2 on 2025-04-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_bet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='option',
            field=models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('draw', 'Draw')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
