# Generated by Django 5.2 on 2025-04-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_bet_option'),
        ('matches', '0004_match_chance_draw_alter_match_odds_draw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='matches.match', verbose_name='Матч'),
        ),
    ]
