# Generated by Django 5.2 on 2025-04-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_alter_bet_match'),
        ('matches', '0004_match_chance_draw_alter_match_odds_draw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('draw', 'Draw')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_options', to='matches.match')),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.betoption'),
        ),
    ]
