# Generated by Django 5.2 on 2025-04-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_betoption_alter_bet_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='chosen_winner',
        ),
    ]
